version: '3'

services:

  dev_ubuntu:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: dev_ubuntu
    volumes:
      - ./code:/var/www/html
    ports:
      - "8080:80"
    networks:
      dev_net:

networks:
  dev_net:
